<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Jack_PC" name="testNG.ExListTest" tests="455" failures="43" timestamp="7 Feb 2015 07:03:51 GMT" time="0.486" errors="0">
  <testcase name="testSortArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_2" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMax_1(ExListTest.java:559)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMax_1 -->
  <testcase name="testSet_1" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testReversArr_many(ExListTest.java:742)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReversArr_many -->
  <testcase name="testAddStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_0" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testSize_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testDelPos_many(ExListTest.java:373)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testDelPos_many -->
  <testcase name="testMin_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMin_many(ExListTest.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMin_many -->
  <testcase name="testAddEnd_0" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testClear_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSize_1(ExListTest.java:440)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSize_1 -->
  <testcase name="testInit_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_1" time="0.031" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMinIndex_1(ExListTest.java:677)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMinIndex_1 -->
  <testcase name="testMax_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testToArray_1(ExListTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testToArray_1 -->
  <testcase name="testGet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSortArr_2(ExListTest.java:778)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSortArr_2 -->
  <testcase name="testMin_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_many" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testToArray_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_NULL" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testSet_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSet_2(ExListTest.java:489)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSet_2 -->
  <testcase name="testAddEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testInit_2(ExListTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testInit_2 -->
  <testcase name="testDelEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testAddPos_many(ExListTest.java:240)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddPos_many -->
  <testcase name="testDelStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testGet_1(ExListTest.java:520)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testGet_1 -->
  <testcase name="testMax_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMinIndex_2(ExListTest.java:686)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMinIndex_2 -->
  <testcase name="testClear_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testTEMP" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_0" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testAddPos_2(ExListTest.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddPos_2 -->
  <testcase name="testMaxIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSize_2(ExListTest.java:449)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSize_2 -->
  <testcase name="testMaxIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testInit_1(ExListTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testInit_1 -->
  <testcase name="testAddPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testDelStart_2(ExListTest.java:274)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testDelStart_2 -->
  <testcase name="testDelStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMaxIndex_1(ExListTest.java:634)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMaxIndex_1 -->
  <testcase name="testSet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_many" time="0.031" classname="testNG.ExListTest"/>
  <testcase name="testSize_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testGet_2(ExListTest.java:529)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testGet_2 -->
  <testcase name="testDelStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_1" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_NULL" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testTEMP" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMaxIndex_many(ExListTest.java:652)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMaxIndex_many -->
  <testcase name="testAddPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testDelStart_many(ExListTest.java:285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testDelStart_many -->
  <testcase name="testMax_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMinIndex_many(ExListTest.java:695)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMinIndex_many -->
  <testcase name="testDelEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_NULL" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_many" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_many" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testSize_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSize_many(ExListTest.java:458)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSize_many -->
  <testcase name="testReversArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMaxIndex_2(ExListTest.java:643)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMaxIndex_2 -->
  <testcase name="testAddPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_2" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_0" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_2" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testSet_many" time="0.016" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSet_many(ExListTest.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSet_many -->
  <testcase name="testClear_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMax_many(ExListTest.java:575)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMax_many -->
  <testcase name="testGet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_NULL" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testMin_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testReversArr_2(ExListTest.java:731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReversArr_2 -->
  <testcase name="testToArray_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_1" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testGet_many(ExListTest.java:538)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testGet_many -->
  <testcase name="testDelEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testReversArr_1(ExListTest.java:720)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testReversArr_1 -->
  <testcase name="testReversArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testAddStart_many(ExListTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddStart_many -->
  <testcase name="testClear_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testToArray_2(ExListTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testToArray_2 -->
  <testcase name="testAddStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_1" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testToArray_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMin_2(ExListTest.java:604)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMin_2 -->
  <testcase name="testInit_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testInit_many(ExListTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testInit_many -->
  <testcase name="testMax_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testTEMP" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at testNG.ExListTest.testTEMP(ExListTest.java:798)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testTEMP -->
  <testcase name="testSortArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_many" time="0.094" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSortArr_1(ExListTest.java:768)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSortArr_1 -->
  <testcase name="testMax_2" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMax_2(ExListTest.java:567)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMax_2 -->
  <testcase name="testDelPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testDelEnd_many(ExListTest.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testDelEnd_many -->
  <testcase name="testAddEnd_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="3">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 3
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testClear_many(ExListTest.java:416)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testClear_many -->
  <testcase name="testSize_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testTEMP" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testToArray_many(ExListTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testToArray_many -->
  <testcase name="testDelPos_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_NULL" time="0.016" classname="testNG.ExListTest"/>
  <testcase name="testGet_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddPos_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testAddPos_1(ExListTest.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAddPos_1 -->
  <testcase name="testDelStart_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSize_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testTEMP" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMax_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testClear_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMaxIndex_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testAddStart_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMinIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testToArray_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_many" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSortArr_many(ExListTest.java:788)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSortArr_many -->
  <testcase name="testToArray_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_1" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testMin_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testMin_1(ExListTest.java:596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testMin_1 -->
  <testcase name="testMaxIndex_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_NULL" time="0.015" classname="testNG.ExListTest"/>
  <testcase name="testDelStart_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSortArr_2" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testInit_many" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelPos_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_1" time="0.000" classname="testNG.ExListTest">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="0">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 0
	at listS.AList1.addEnd(AList1.java:134)
	at listS.AList1.init(AList1.java:23)
	at listS.AList1.setArray(AList1.java:9)
	at testNG.ExListTest.testSet_1(ExListTest.java:480)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testSet_1 -->
  <testcase name="testMin_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testReversArr_0" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testDelEnd_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testSet_NULL" time="0.000" classname="testNG.ExListTest"/>
  <testcase name="testGet_0" time="0.000" classname="testNG.ExListTest"/>
</testsuite> <!-- testNG.ExListTest -->
